lib/savefile.h, lib/sdcard_startup.h
=> implement filter knobs 

lib/audio_callback.h, lib/savefile.h, lib/zeptocore.h
=> add depth to the circulate

lib/audio_callback.h, lib/savefile.h
=> add heighten depth

lib/resonantfilter.h
=> correctly initialize resonant filter

docs/content/combos/tempo-tap.md, lib/zeptocore.h
=> set bpm so that middle knob is the sample original bpm

docs/content/combos/retrigger.md, docs/content/effects/retrigtype.md, lib/definitions.h, lib/savefile.h, main.c
=> FX 15 can control the retriggering behavior

core/src/server/static/app.js, core/src/server/static/index.html, core/src/server/static/style.css
=> add .selected_on to indicate which file is open

.github/workflows/release.yml, .gitignore, Makefile, boardcore_compile_definitions.cmake, lib/boardcore.h, main.c
=> add release for boardcore version

README.md, docs/content/combos/pitch.md, lib/zeptocore.h
=> put pitch to unity

lib/globals.h, lib/sdcard_startup.h
=> fixed toggling off tape stop when pitch fx is on doesn't go to correct pitch

lib/audio_callback.h, lib/resonantfilter.h, lib/zeptocore.h
=> fix filter popping bug

core/src/server/static/app.js, core/src/server/static/index.html
=> core: clicking one-shot changes playback mode, Fixes #215

lib/audio_callback.h, lib/ectocore.h, lib/globals.h, lib/savefile.h, lib/sdcard_startup.h, lib/zeptocore.h
=> pitch part of savefile Fixes #213

main.c
=> fix retrig pitch causes instability

lib/audio_callback.h
=> prevent from scratch from sampling nothing

lib/comb.h
=> fix comb leveling

lib/freeverb_fp_mono.h, lib/includes.h, lib/savefile.h
=> switch reverb to mono to save cpu

lib/zeptocore.h
=> fix: sequencer only seems to be able to work quantization over the first sequence stored

lib/button_handler.h
=> fix bass from activating when pressing other buttons

docs/content/blurbs/about.md, docs/content/blurbs/source-code.md, docs/content/blurbs/uploading-samples.md, docs/content/combos/random_jump.md, docs/content/combos/random_retrig.md, docs/content/combos/tempo_match.md, docs/content/effects/_index.md, docs/content/quickstart/_index.md
=> docs - typos

core/src/server/static/index.html, core/src/server/static/style.css
=> expand drop zone if there are no files

docs/content/blurbs/uploading-samples.md
=> add xattrc -c to the macos instructions

docs/content/combos/sequence_record.md
=> explain the sequencer Fixes #260

docs/content/quickstart/_index.md
I'm actually going trough the manual with the device and caught this :-)
=> docs correction: changing banks and samples

lib/savefile.h
=> fix sequencer saving and loading

lib/button_handler.h
=> show which samples are in bank when bank is selected

lib/button_handler.h, lib/globals.h, lib/zeptocore.h
=> visual feedback for changing pitch

Makefile, lib/button_handler.h
=> show current selected sample when selecting bank

core/src/zeptocore/zeptocore.go
=> core: fix one-shot mode setting in browser

core/src/server/merge.go
=> core: create more spacing when merging samples

main.c
=> boardcore: fix cpu frequency for longer wires

lib/zeptocore.h
=> slightly improve button response time

docs/themes/zeptocore/static/static/midistuff.js, lib/fuzz.h, lib/midi_comm_callback.h, lib/saturation.h, lib/savefile.h, main.c
=> add mute and play/stop to the midi controls

docs/content/combos/bass_volume.md, docs/content/combos/filter_sweep.md, docs/content/combos/knob_x_b.md, docs/content/combos/random_tunnel.md, docs/themes/zeptocore/layouts/_default/baseof.html, lib/button_handler.h, lib/globals.h, lib/zeptocore.h, main.c
=> D + Knob Z will now change probability of tunneling

Makefile, docs/content/blurbs/midi.md, docs/content/blurbs/source-code.md, lib/midi_out.h, lib/zeptocore.h
=> midi cc added for each knob combination

docs/themes/zeptocore/static/static/midistuff.js
=> fix midistuff.js to do calls only if midi has been set up

lib/wavetablebass.h, lib/wavetablesyn.h
=> better bass defaults

CMakeLists.txt, docs/content/blurbs/midi.md, docs/themes/zeptocore/assets/css/main.css, lib/audio_callback.h, lib/button_handler.h, lib/clock_input.h, lib/clockhandling.h, lib/globals.h, lib/includes.h, lib/midi_comm.h, lib/midicallback.h, lib/onewiremidi.h, lib/zeptocore.h, main.c
=> midi usb and itty bitty midi working

main.c, zeptocore_compile_definitions.cmake
=> show top led on the zeptocore

.gitignore, core/src/server/server.go, dev/flash.sh, docs/content/blurbs/source-code.md, docs/content/blurbs/uploading-samples.md, docs/themes/zeptocore/layouts/_default/baseof.html, lib/button_handler.h, lib/ectocore.h, lib/globals.h, lib/midi_comm.h, lib/zeptocore.h, main.c
=> add fill mode

docs/content/combos/combo_fill.md, docs/content/combos/combo_rand.md, main.c
=> new: regenerate sequence if fill + rand is activated

lib/midicallback.h
=> fix: midi continue -> midi start

lib/ectocore.h
=> ectocore: reset device when bank + mode + mult buttons held

lib/button_handler.h, lib/ectocore.h, lib/globals.h, main.c
=> ectocore: rungler implemented for amen attenuator, fix timestretch, more break knob

lib/ectocore.h, lib/globals.h, lib/zeptocore.h
=> fix the per-step probability of the jump efect

lib/ectocore.h
=> ectocore: fix sample cv, add break cv

ectocore_compile_definitions.cmake, lib/ectocore.h
=> fix: setup mode led button lights

docs/content/combos/tempo-tap.md, lib/button_handler.h, lib/zeptocore.h
=> zeptocore: hold A+B to set predefined tempo

docs/content/combos/combo_rand.md, lib/button_handler.h, lib/globals.h
=> zeptocore: holding button while in RAND makes new sequence

lib/button_handler.h, lib/globals.h
=> holding a single key does single retrigger

lib/array_resample.h, lib/audio_callback.h, lib/savefile.h, lib/zeptocore.h
=> fix: easier to set bpm

lib/ectocore.h, lib/sdcard_startup.h
=> ecotcore: fix timestretching

lib/ectocore.h
=> ectocore: better lighting with gogglefrog

lib/globals.h, lib/sdcard_startup.h
=> zeptocore: disable reverb if too many samples

lib/dazzle.h, lib/ectocore.h, lib/includes.h
=> ectocore: add dazzling visualziations

lib/button_handler.h, lib/savefile.h, lib/sdcard_startup.h
=> fix: saving/loading glitch removed

lib/ectocore.h
=> ectocore: tap bank to iterate through banks

core/src/zeptocore/zeptocore.go, lib/button_handler.h
=> zeptocore: B + A while RAND is on changes one note each time combo is used

core/src/drumextract/drumextract.go, core/src/server/server.go, core/src/server/static/app.js, core/src/server/static/index.html, core/src/server/static/style.css, core/src/zeptocore/zeptocore.go
=> web: allow easy creation of one-shot samples with toggle

core/src/server/static/app.js, core/src/server/static/index.html
=> add some helpful tooltips

lib/midi_comm.h, main.c
=> zeptocore: midi sync with clock out and start/stop

CMakeLists.txt, Makefile, lib/ectocore.h, lib/ectocore_flash.h, lib/flashmem.h, lib/globals.h, lib/includes.h, lib/zeptocore.h, main.c
=> ectocore: calibration saves/restores from the flash memory, not SD card

lib/ectocore.h, lib/globals.h
=> ectocore: amen does freezing instead of probability, atten does random / lock

lib/taptempo.h
=> require two taps to change the tempo

lib/ectocore.h
=> ectocore: volume indicator and better leveling

ectocore_compile_definitions.cmake, lib/WS2812.h, lib/ectocore.h
=> ectocore: add global brightness control to the ws2812

core/.air.toml, core/main.go, core/src/server/server.go, core/src/server/static/app.js, core/src/server/static/index.html, core/src/server/static/style.css
=> web: create switch for ectocore

lib/ectocore.h
=> ectocore: show current bank when holding bank button

core/.air.toml, core/src/server/server.go, core/src/server/static/index.html
=> zeptocore: add setting to change sample as global setting

docs/content/contact/contact.md, docs/themes/zeptocore/layouts/_default/baseof.html
=> web: add zeptocore.com/#contact

lib/WS2812.h, lib/sdcard_startup.h
=> ectocore: internally limit ws2812 brightess to 50% max

lib/ectocore.h
=> ectocore: Mult button should divide down after one second of holding

lib/sdcard_startup.h
=> zeptocore: fix clock stop sync to default to on

lib/ectocore.h, lib/knob_change.h
=> ectocore: improve knob precision

lib/ectocore.h, lib/includes.h, main.c
=> ectocore: tap+mult stops and tap restart

lib/zeptocore.h
=> zeptocore: B+X changes random sequence

core/src/pack/pack.go, core/src/server/static/app.js, core/src/server/static/index.html, lib/ectocore.h, lib/globals.h, lib/sdcard_startup.h, main.c
=> ectocore: add setting to change clock output between gate and trig

lib/audio_callback.h, lib/ectocore.h, lib/resonantfilter.h, lib/resonantfilter.py, lib/zeptocore.h
=> zeptocore & ecotocore: add DJ style low/high-pass filter

lib/ectocore.h
=> ectocore: reduce brightness of break knob leds

lib/ectocore.h, lib/taptempo.h
=> ectocore: hold tap, press mult to start/stop (pressing tap after stop also works)

lib/ectocore.h
=> ectocore: tap + sample does gating

lib/ectocore.h
=> ectocore: fix volume drop when moving to distortion

Makefile, core/src/pack/pack.go, core/src/server/static/app.js, core/src/server/static/index.html, lib/globals.h, lib/sdcard_startup.h, main.c
=> ectocore: option to clock out with bpm instead of slice (now default)

lib/zeptocore.h
=> zeptocore: improve timestretch stability

lib/clockhandling.h, lib/ectocore.h, lib/globals.h
=> ectocore: tap tempo button resets to 1 when clock signal present

lib/ectocore.h
=> ectocore: fix volume -> saturation -> distortion leveling

lib/button_handler.h
=> zeptocore: B+A+[1-16] can customize the random sequence

lib/flashmem.h, lib/sdcard_startup.h, lib/utils.h, lib/zeptocore.h
=> zeptocore & ectocore: code cleanup

lib/ectocore.h
=> ectocore: fix distortion overloading filter

lib/globals.h, lib/random.h, lib/random_seeded.h, lib/test/random_seeded/main.c
=> fix: random_sequence_in_range should be inclusive

core/src/sox/sox.go, core/src/sox/sox_test.go
=> sox: add warp function

lib/break_knob.h, lib/ectocore.h
=> ectocore: fix sample selection

lib/audio_callback.h, lib/ectocore.h, lib/globals.h, lib/zeptocore.h, main.c
=> ectocore: fix low-pass effect to not remove high-pass if it is enabled

core/src/pack/pack.go, core/src/server/server.go, core/src/server/static/app.js, core/src/server/static/index.html
=> core: download only the settings

core/src/server/static/app.js
=> web: fix slice creation tool to prevent 0 slices

Makefile, lib/button_handler.h, lib/buttonmatrix3.h
=> zeptocore: responsive buttons

lib/button_handler.h, lib/buttonmatrix3.h, lib/globals.h, lib/zeptocore.h, main.c
=> zeptocade: program the knob placements

lib/midi_comm.h
=> fix midi bug (midi stops after ~ 1 minute)

core/go.mod, core/go.sum, core/src/drumextract2/drumextract2.go, core/src/server/server.go, core/src/utils/utils.go, core/src/zeptocore/zeptocore.go
=> core: allow determining offsets in cloud

core/src/onsetdetect/onsetdetect.go, core/src/server/server.go
=> core: provide auto splicing in the cloud

core/src/server/server.go
=> core: prevent states.db from corrupting

docs/content/blurbs/midi.md, docs/content/combos/midi_in.md
=> docs: need to add information about switching to MIDI in on clock input

lib/ectocore.h
=> ectocore: add button combo (hold TAP + press MODE) to return to original sample speed

.github/workflows/release.yml, Makefile, core/main.go
=> ectocore: add builds to the releases

lib/ectocore.h
=> ectocore: moving banks should change position based on knob

lib/audio_callback.h, lib/button_handler.h, lib/globals.h, lib/zeptocore.h, main.c
=> ectocore: amiga mode (12khz filtered + downsampled?)

core/src/pack/pack.go, lib/audio_callback.h, lib/ectocore.h, lib/sdcard_startup.h, lib/test/structs/main.c, lib/zeptoboard.h, lib/zeptocore.h
=> core: banks should start at 1 (breaking change!)

core/src/pack/pack.go, core/src/server/static/app.js, core/src/server/static/index.html, core/src/server/static/style.css
=> web: allow easier editing of the trig transients

lib/ectocore.h, main.c
=> ectocore: calibrate by holding TAP + BANK

lib/audio_callback.h, lib/break_knob.h, lib/ectocore.h
=> ectocore: fixed freezing at high bpm with reverse + retrigger with pitch shift

docs/content/blurbs/uploading-samples.md
=> core: add morphagene slice parser

core/src/server/server.go, core/src/server/static/app.js, core/src/server/static/style.css
=> web: fix upload progress bar

lib/ectocore.h
=> ectocore: tap+mode is a reset to first beat

lib/break_knob.h, lib/sdcard_startup.h
=> ectocore: fix: pitch down is unrecoverable

.github/workflows/build.yml, .github/workflows/release.yml, Makefile
=> zeptocore: fix: bass synth produces a light crackle on the release stage of the envelope

lib/globals.h, lib/zeptocore.h
=> zeptocore: stop when clock in stops

lib/audio_callback.h, lib/fixedpoint.h
=> core: add fade in/out of the reverb effect

lib/dazzle.h, lib/ectocore.h
=> ectocore: add reverb leds

lib/resonantfilter.h, lib/resonantfilter.py, lib/volume.h
=> fix: increase stability of filter

lib/sdcard.h, lib/sdcard_startup.h
=> core: add "no sd card" indicators

lib/ectocore.h, main.c
=> ectocore: bipolar amen (<0 trigs on time, >0 trigs on voltage change)

core/.air.toml, core/src/pack/pack.go, core/src/server/static/app.js, core/src/server/static/index.html, lib/ectocore.h, lib/globals.h, lib/sdcard_startup.h
=> ectocore: add options for Amen CV input

lib/ectocore.h
=> ectocore: fix tap tempo after clocking bug

core/src/pack/pack.go, core/src/server/static/app.js, core/src/server/static/index.html, core/src/server/static/style.css, lib/ectocore.h, lib/globals.h, lib/sdcard_startup.h
=> ectocore: add options for CV in polarity

core/src/chapters/chapters.go, core/src/op1/op1.go, core/src/renoise/renoise.go
=> web: prevent panics in gathering slices

lib/ectocore.h
=> ectocore: fixed Fatal crash discovered when quick bank selecting with holding bank + turning Sample

lib/audio_callback.h, lib/button_handler.h, lib/ectocore.h, lib/knob_change.h, lib/zeptocore.h
=> fix: reset knob debouncer when unpressing buttons

lib/ectocore.h
=> ectocore: Amen knob is at a power of 2 division, the display is green instead of yellow

lib/ectocore.h, lib/globals.h, lib/zeptocore.h, main.c
=> core: add more sequences to random generators

main.c
=> core: variable mode should not sync by default

lib/ectocore.h
=> ectocore: fix fast bank switching bug

lib/flashmem.h
=> ectocore: prevent calibration from being overwritten #693

lib/array_resample.h, lib/audio_callback.h, lib/ectocore.h, lib/my_pico_audio/audio.cpp, lib/resonantfilter.h, lib/saturation.h, lib/shaper.h, lib/zeptocore.h
=> feat: reduce cpu usage by moving common fucntions to ram

CMakeLists.txt, lib/ectocore.h, lib/sdcard_startup.h
=> fix: prevent breaking through case, add O3 optimizations

lib/audio_callback.h
=> fix: statically allocate the resampling array

lib/ectocore.h
=> feat: quickly change sample on cv in

lib/ectocore.h, lib/globals.h
=> feat: implement reset in the ectocore

lib/ectocore.h
=> fix: reset cv works with clock in simultaneously

main.c
=> fix: double triggers when externally clocking at 48 pulses per slice

lib/sdcard_startup.h
=> fix: make sure sample knob works when using reset in sample override

lib/ectocore.h
=> fix: allow amen knob functionality when using reset through amen cv in

lib/clockhandling.h, lib/ectocore.h
=> fix: reduce latency in the clock starting

README.md
I struggled to find the procedure for updating the ectocore. Therefore, I thought it would be useful to include it in the readme file.
I hope this helps. 🤘
=> add ectocore update process in README

lib/ectocore.h
=> fix: improve external clocking latency by ~1-2ms

lib/knob_change.h
=> improve knob filtering
